# Generated by Django 5.2.4 on 2025-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
