# Generated by Django 5.2.4 on 2025-07-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Usuarios', '0003_alter_cliente_telefono_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
