# Generated by Django 5.2.4 on 2025-08-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Usuarios', '0005_rename_fecha_nacimiento_cliente_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
