# Generated by Django 5.2.4 on 2025-08-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Usuarios', '0007_alter_cliente_dni_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
